global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using ProdavnicaLibrary.Entiteti;
global using ProdavnicaLibrary.DTOs;
global using NHibernate;
global using static ProdavnicaLibrary.Extensions;
global using System.Diagnostics.CodeAnalysis;